version: '3.8'

services:
  data-populator:
    build:
      context: ../..
      dockerfile: apps/data-populator/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - PORT=8080
      - PINATA_JWT_KEY
      - PINATA_GATEWAY_KEY
      - IPFS_GATEWAY
      - ATTEST_CONTRACT_ADDRESS=0x430BbF52503Bd4801E51182f4cB9f8F534225DE5
      - ATTEST_CONTRACT_ADDRESS_DEV=0x1A6950807E33d5bC9975067e6D6b5Ea4cD661665
      - MULTIVAULT_CONTRACT_ADDRESS=0x430BbF52503Bd4801E51182f4cB9f8F534225DE5
      - MULTIVAULT_CONTRACT_ADDRESS_DEV=0x1A6950807E33d5bC9975067e6D6b5Ea4cD661665
      - PRIVATE_KEY
      - PRIVATE_KEY_DEV
      - EVM_RPC
      - EVM_RPC_DEV
      - ADDITIONAL_STAKE_ATOM=100000000000
      - ADDITIONAL_STAKE_TRIPLE=100000000000
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
      - SUPABASE_URL
      - SUPABASE_KEY
      - ENVIRONMENT
      - MULTIVAULT_ADDRESS_BASE_SEPOLIA
      - MULTIVAULT_ADDRESS_BASE_MAINNET
      - ALCHEMY_MAINNET_API_KEY
      - ALCHEMY_API_KEY
      - ALCHEMY_MAINNET_RPC_URL
      - ALCHEMY_OP_SEPOLIA_RPC_URL
      - ALCHEMY_BASE_SEPOLIA_RPC_URL
      - ALCHEMY_BASE_RPC_URL
      - WALLETCONNECT_PROJECT_ID
      - SESSION_SECRET
      - API_URL=https://api.intuition.systems
      - API_KEY
      - AWS_SECRET_KEY
      - AWS_ACCESS_KEY
      - STORAGE_REGION
      - STORAGE_BUCKET
      - ADMIN_PRIVATE_KEY
      - CLAIMR_AUTH_TOKEN
      - CLAIMR_CAMPAIGN_ID
      - ORIGIN_URL=https://portal.intuition.systems
      - PRIVY_APP_ID
      - PRIVY_AUTH_URL
      - PRIVY_APP_SECRET
      - SENTRY_AUTH_TOKEN
      - SENTRY_DSN
      - SENTRY_ORG
      - SENTRY_PROJECT
      - VITE_DEPLOY_ENV=production
      - FF_FULL_LOCKDOWN_ENABLED=false
      - FF_INCIDENT_BANNER_ENABLED=false
      - FF_GENERIC_BANNER_ENABLED=false
