name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 9.0.6
      # Foundry setup for protocol
      - name: Set up foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            **/node_modules/.pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v3
      - name: Run Affected Lint
        if: github.event_name == 'pull_request'
        run: pnpm nx affected -t lint --base=origin/main~1 --head=origin/main
      - name: Run Affected Tests
        if: github.event_name == 'pull_request'
        run: pnpm nx affected -t test --base=origin/main~1 --head=origin/main
      - name: Run Affected Builds
        if: github.event_name == 'pull_request'
        run: pnpm nx affected -t build --base=origin/main~1 --head=origin/main
      - name: Build 1ui Storybook
        if: github.ref == 'refs/heads/main'
        run: pnpm 1ui:build-storybook
      - name: Deploy 1ui Storybook
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/storybook/1ui
